// Generated by tools/precache.mjs — do not edit by hand.
self.EKFBA_PRECACHE = {
  "version": "1d202e7592d8",
  "files": [
    "./",
    "./icons/apple-touch-icon.png",
    "./icons/icon-192.png",
    "./icons/icon-512.png",
    "./icons/icon.svg",
    "./icons/maskable-512.png",
    "./index.html",
    "./manifest.webmanifest",
    "./src/core/backup.js",
    "./src/core/card.js",
    "./src/core/crypto.js",
    "./src/core/feedates.js",
    "./src/core/ids.js",
    "./src/core/money.js",
    "./src/core/rulepack.js",
    "./src/core/schema.js",
    "./src/core/sensitive.js",
    "./src/data/db.js",
    "./src/data/repo.js",
    "./src/ui/app.js",
    "./src/ui/html.js",
    "./src/ui/router.js",
    "./src/ui/screens/cards.js",
    "./src/ui/screens/home.js",
    "./src/ui/screens/settings.js",
    "./src/ui/screens/upcoming.js",
    "./src/ui/styles.css",
    "./src/ui/ui-kit.js"
  ]
};
