// Service worker: makes the app shell available offline.
// The precache list and version come from precache.js, regenerated by tools/precache.mjs
// whenever any app file changes (a test fails if it is out of date).

importScripts('./precache.js'); // defines self.EKFBA_PRECACHE = { version, files }

const { version, files } = self.EKFBA_PRECACHE;
const CACHE = `ekfba-shell-${version}`;

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(files.map((f) => new Request(f, { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('ekfba-shell-') && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // never cache third-party responses

  // Navigations: serve the cached shell (hash routing means every screen is index.html).
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cached = await caches.match('./index.html', { cacheName: CACHE });
      if (cached) return cached;
      return fetch(req);
    })());
    return;
  }

  // App files: cache-first; new versions arrive via a new service worker + precache list.
  event.respondWith((async () => {
    const cached = await caches.match(req, { cacheName: CACHE, ignoreSearch: true });
    return cached || fetch(req);
  })());
});
