// Merchant and category directory used to understand "where are you spending".
// Data only — the Flutter app can load the same list. Categories come from the Rule Pack vocabulary.

/** { name, aliases, categories, channel } — channel: 'online' | 'offline' | 'any' */
export const MERCHANTS = [
  // Electronics
  { name: 'Croma', aliases: [], categories: ['electronics'], channel: 'any' },
  { name: 'Reliance Digital', aliases: ['reliance digital'], categories: ['electronics'], channel: 'any' },
  { name: 'Vijay Sales', aliases: [], categories: ['electronics'], channel: 'any' },
  { name: 'Bajaj Electronics', aliases: [], categories: ['electronics'], channel: 'any' },
  { name: 'Apple Store', aliases: ['apple'], categories: ['electronics'], channel: 'any' },
  // Online shopping and fashion
  { name: 'Amazon', aliases: ['amazon.in'], categories: ['online_shopping'], channel: 'online' },
  { name: 'Flipkart', aliases: [], categories: ['online_shopping'], channel: 'online' },
  { name: 'Myntra', aliases: [], categories: ['apparel', 'online_shopping'], channel: 'online' },
  { name: 'Ajio', aliases: [], categories: ['apparel', 'online_shopping'], channel: 'online' },
  { name: 'Nykaa', aliases: [], categories: ['online_shopping'], channel: 'online' },
  { name: 'Meesho', aliases: [], categories: ['online_shopping'], channel: 'online' },
  { name: 'TATA CLiQ', aliases: ['tata cliq', 'tatacliq'], categories: ['online_shopping'], channel: 'online' },
  { name: 'Lifestyle', aliases: [], categories: ['apparel', 'department_store'], channel: 'any' },
  { name: 'Pantaloons', aliases: [], categories: ['apparel'], channel: 'any' },
  { name: 'Westside', aliases: [], categories: ['apparel'], channel: 'any' },
  { name: 'Shoppers Stop', aliases: [], categories: ['apparel', 'department_store'], channel: 'any' },
  { name: 'Trends', aliases: ['reliance trends'], categories: ['apparel'], channel: 'offline' },
  { name: 'Max Fashion', aliases: [], categories: ['apparel'], channel: 'offline' },
  { name: 'Decathlon', aliases: [], categories: ['department_store'], channel: 'any' },
  { name: 'IKEA', aliases: [], categories: ['department_store'], channel: 'any' },
  { name: 'Tanishq', aliases: [], categories: ['jewellery'], channel: 'any' },
  { name: 'Malabar Gold', aliases: ['malabar'], categories: ['jewellery'], channel: 'offline' },
  // Groceries
  { name: 'Swiggy Instamart', aliases: ['instamart'], categories: ['grocery'], channel: 'online' },
  { name: 'Blinkit', aliases: [], categories: ['grocery'], channel: 'online' },
  { name: 'Zepto', aliases: [], categories: ['grocery'], channel: 'online' },
  { name: 'BigBasket', aliases: ['big basket', 'bb now'], categories: ['grocery'], channel: 'online' },
  { name: 'Flipkart Minutes', aliases: [], categories: ['grocery'], channel: 'online' },
  { name: 'Amazon Fresh', aliases: [], categories: ['grocery'], channel: 'online' },
  { name: 'DMart', aliases: ['d mart', 'd-mart', 'dmart ready'], categories: ['grocery'], channel: 'any' },
  { name: 'Ratnadeep', aliases: ['ratnadeep supermarket'], categories: ['grocery'], channel: 'offline' },
  { name: 'More Supermarket', aliases: ['more retail', 'more megastore'], categories: ['grocery'], channel: 'offline' },
  { name: 'Spencer\'s', aliases: ['spencers'], categories: ['grocery'], channel: 'offline' },
  { name: 'Reliance Smart', aliases: ['reliance fresh', 'smart bazaar', 'reliance smart bazaar'], categories: ['grocery'], channel: 'offline' },
  { name: 'Vijetha Supermarket', aliases: ['vijetha'], categories: ['grocery'], channel: 'offline' },
  { name: 'Star Bazaar', aliases: [], categories: ['grocery'], channel: 'offline' },
  // Food
  { name: 'Swiggy', aliases: [], categories: ['food_delivery'], channel: 'online' },
  { name: 'Zomato', aliases: [], categories: ['food_delivery'], channel: 'online' },
  { name: 'Domino\'s', aliases: ['dominos'], categories: ['dining'], channel: 'any' },
  { name: 'McDonald\'s', aliases: ['mcdonalds'], categories: ['dining'], channel: 'any' },
  { name: 'KFC', aliases: [], categories: ['dining'], channel: 'any' },
  { name: 'Starbucks', aliases: [], categories: ['dining'], channel: 'offline' },
  { name: 'Paradise Biryani', aliases: ['paradise'], categories: ['dining'], channel: 'any' },
  // Entertainment
  { name: 'BookMyShow', aliases: ['book my show', 'bms'], categories: ['entertainment'], channel: 'online' },
  { name: 'PVR INOX', aliases: ['pvr', 'inox'], categories: ['entertainment'], channel: 'any' },
  { name: 'District', aliases: ['district by zomato'], categories: ['entertainment'], channel: 'online' },
  // Travel
  { name: 'MakeMyTrip', aliases: ['make my trip', 'mmt'], categories: ['travel'], channel: 'online' },
  { name: 'Goibibo', aliases: [], categories: ['travel'], channel: 'online' },
  { name: 'Cleartrip', aliases: [], categories: ['travel'], channel: 'online' },
  { name: 'EaseMyTrip', aliases: ['ease my trip'], categories: ['travel'], channel: 'online' },
  { name: 'Yatra', aliases: [], categories: ['travel'], channel: 'online' },
  { name: 'Axis Bank Travel EDGE', aliases: ['travel edge', 'axis travel edge'], categories: ['travel', 'flights'], channel: 'online' },
  { name: 'IRCTC', aliases: ['train ticket', 'railway'], categories: ['travel'], channel: 'online' },
  { name: 'IndiGo', aliases: ['indigo'], categories: ['flights'], channel: 'any' },
  { name: 'Air India', aliases: ['air india express'], categories: ['flights'], channel: 'any' },
  { name: 'Akasa Air', aliases: ['akasa'], categories: ['flights'], channel: 'any' },
  { name: 'Taj Hotels', aliases: ['taj', 'ihcl'], categories: ['hotels'], channel: 'any' },
  { name: 'Marriott', aliases: [], categories: ['hotels'], channel: 'any' },
  { name: 'OYO', aliases: [], categories: ['hotels'], channel: 'online' },
  { name: 'Uber', aliases: [], categories: ['transport'], channel: 'online' },
  { name: 'Ola', aliases: [], categories: ['transport'], channel: 'online' },
  { name: 'Rapido', aliases: [], categories: ['transport'], channel: 'online' },
  { name: 'FASTag', aliases: ['fastag', 'toll'], categories: ['transport'], channel: 'online' },
  // Fuel
  { name: 'Indian Oil', aliases: ['iocl', 'indianoil'], categories: ['fuel'], channel: 'offline' },
  { name: 'HP Petrol Pump', aliases: ['hpcl', 'hp petrol', 'hindustan petroleum'], categories: ['fuel'], channel: 'offline' },
  { name: 'Bharat Petroleum', aliases: ['bpcl'], categories: ['fuel'], channel: 'offline' },
  { name: 'Shell', aliases: [], categories: ['fuel'], channel: 'offline' },
  { name: 'Jio-bp', aliases: ['jio bp', 'jiobp'], categories: ['fuel'], channel: 'offline' },
  // Health
  { name: 'Apollo Pharmacy', aliases: ['apollo'], categories: ['healthcare'], channel: 'any' },
  { name: 'MedPlus', aliases: ['med plus'], categories: ['healthcare'], channel: 'any' },
  { name: 'PharmEasy', aliases: [], categories: ['healthcare'], channel: 'online' },
  { name: 'Tata 1mg', aliases: ['1mg'], categories: ['healthcare'], channel: 'online' },
  // Bills and others
  { name: 'Airtel', aliases: [], categories: ['telecom'], channel: 'online' },
  { name: 'Jio', aliases: ['jio recharge'], categories: ['telecom'], channel: 'online' },
  { name: 'Vodafone Idea', aliases: ['vi recharge'], categories: ['telecom'], channel: 'online' },
  { name: 'LIC', aliases: ['lic premium'], categories: ['insurance'], channel: 'online' },
  { name: 'Amazon Pay wallet', aliases: ['paytm wallet', 'wallet load'], categories: ['wallet_load'], channel: 'online' },
];

/** Words that name a category when no merchant matches. */
export const CATEGORY_WORDS = {
  grocery: ['grocery', 'groceries', 'supermarket', 'kirana', 'vegetables'],
  dining: ['restaurant', 'dining', 'dinner', 'lunch', 'cafe', 'hotel food', 'eating out'],
  food_delivery: ['food delivery', 'food order'],
  fuel: ['petrol', 'diesel', 'fuel', 'petrol pump', 'cng'],
  travel: ['travel', 'holiday', 'trip', 'bus ticket'],
  flights: ['flight', 'flights', 'air ticket', 'airline'],
  hotels: ['hotel', 'hotel stay', 'hotel booking', 'resort'],
  transport: ['cab', 'taxi', 'auto', 'metro', 'toll'],
  electronics: ['electronics', 'mobile phone', 'laptop', 'tv', 'television', 'fridge', 'washing machine', 'ac'],
  apparel: ['clothes', 'clothing', 'apparel', 'fashion', 'shoes'],
  online_shopping: ['online shopping'],
  utilities: ['electricity', 'power bill', 'water bill', 'gas bill', 'utility', 'utilities', 'broadband'],
  telecom: ['mobile recharge', 'recharge', 'postpaid'],
  rent: ['rent', 'house rent'],
  insurance: ['insurance', 'premium'],
  education: ['school fee', 'school fees', 'college fee', 'tuition', 'education'],
  government: ['tax', 'government', 'challan', 'passport'],
  jewellery: ['jewellery', 'jewelry', 'gold'],
  entertainment: ['movie', 'movies', 'cinema', 'concert', 'event'],
  healthcare: ['pharmacy', 'medicine', 'medicines', 'hospital', 'doctor', 'diagnostic'],
  wallet_load: ['wallet'],
  emi: ['emi'],
};
