// Regenerates precache.js: the list of app files the service worker stores for offline use,
// plus a content hash used as the cache version. Run: node tools/precache.mjs
// With --check it only verifies precache.js is current (used by the test suite).

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = join(fileURLToPath(import.meta.url), '..', '..');
const INCLUDE_DIRS = ['src', 'icons'];
const INCLUDE_FILES = ['index.html', 'manifest.webmanifest'];

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

export function buildPrecache() {
  const files = [...INCLUDE_FILES.map((f) => join(root, f)), ...INCLUDE_DIRS.flatMap((d) => walk(join(root, d)))]
    .map((p) => relative(root, p).split('\\').join('/'))
    .sort();
  const hash = createHash('sha256');
  for (const f of [...files, 'sw.js']) hash.update(f).update(readFileSync(join(root, f)));
  const version = hash.digest('hex').slice(0, 12);
  const content = `// Generated by tools/precache.mjs — do not edit by hand.\nself.EKFBA_PRECACHE = ${JSON.stringify({ version, files: ['./', ...files.map((f) => './' + f)] }, null, 2)};\n`;
  return { version, content };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { version, content } = buildPrecache();
  const target = join(root, 'precache.js');
  if (process.argv.includes('--check')) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== content) { console.error('precache.js is out of date — run: node tools/precache.mjs'); process.exit(1); }
    console.log(`precache.js up to date (${version})`);
  } else {
    writeFileSync(target, content);
    console.log(`precache.js written (${version})`);
  }
}
